name: Deploy to Cloud Run

on:
  push:
    branches:
      - Dev

env:
  PROJECT_ID: deployment-test-414315
  SERVICE_NAME: tbt
  REGION: europe-west9
  IMAGE_NAME: gcr.io/deployment-test-414315/tbt
  TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:$TAG .
        docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

    - name: Push Docker image to Container Registry
      run: |
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image=$IMAGE_NAME:$TAG \
          --platform=managed \
          --region=$REGION \
          --allow-unauthenticated
